### ISSUE TITLE
artisan server shuts down after first request

### ISSUE THREAD

**Issue by cord** [andrewelkins/Laravel-4-Bootstrap-Starter-Site#174]
when calling http://localhost:8000/ the page is displayed without any img/css and the console is prompting. so appears to me artisan serve is shut down.

which php shows /Applications/MAMP/bin/php/php5.4.10/bin/php

it works on other L4 sites.

the page also runs when using the local apache.

any idea how to debug the artisan serve process?

**Comment by tsummerer** [comment]
Try turning off XCache in MAMP. I had the same issue and this solved it for me. So far it's working fine using APC cache instead. There should be a dropdown in the Preferences where you can choose a Cache
