### ISSUE TITLE
Seed Error - Cannot truncate a table referenced in a foreign key constraint

### ISSUE THREAD

**Issue by christoferd** [andrewelkins/Laravel-4-Bootstrap-Starter-Site#227]
The error is happening in the very first seed file, and is happening after a migrate refresh.

**Error:**

---

UsersTableSeeder - run()

  [Exception]
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`database_dev`.`assigned_roles`, CONSTRAINT `assigned_roles_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES
   `database_dev`.`users` (`id`)) (SQL: truncate `users`) (Bindings: array (
  ))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (`database_dev`.`assigned_roles`, CONSTRAINT `assigned_roles_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES
   `database_dev`.`users` (`id`))

db:seed [--class[="..."]] [--database[="..."]]

---

**Reproduce:**
WAMP, Mysql 5.6.14

> php artisan migrate
> php artisan db:seed

---

_Any Ideas?_

**Comment by chegie** [comment]
Thanks, it worked!

**Comment by AnDi1402** [comment]
tengo el mismo error pero no logro solucionarlo, pues la migrating ejecuta muy bien, pero cuando lo hago con los seeders me saca el siguiente error!

`  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a t
  able referenced in a foreign key constraint (`docepublicunac`.`rol_has_pagi
  nas`, CONSTRAINT `rol_has_paginas_id_rol_foreign` FOREIGN KEY (`id_rol`) RE
  FERENCES `docepublicunac`.`rol` (`id`)) (SQL: truncate `rol`)
`
Alguien que me ayude por favor! 

esta es mi codigo en la migración! 

`    public function up()
    {
        Schema::create('rol_has_paginas', function (Blueprint $table) {
            $table->integer('id_rol')->unsigned();
            $table->integer('paginas_idpaginas')->unsigned();
            $table->timestamps();

            $table->foreign('id_rol')
                  ->references('id')
                  ->on('rol');

            $table->foreign('paginas_idpaginas')
                  ->references('id')
                  ->on('paginas');

        });
    }

    public function down()
    {
        Schema::dropIfExists('rol_has_paginas');
    }`
