### ISSUE TITLE
wysiwyg-color.css 404 (Not Found) 

### ISSUE THREAD

**Issue by merolhack** [andrewelkins/Laravel-4-Bootstrap-Starter-Site#342]
Hi, in my Chrome Console i see a broken link to CSS:
GET /lib/css/wysiwyg-color.css 404 (Not Found) 

In the issues of "jhollingworth/bootstrap-wysihtml5" the solution is:
https://github.com/jhollingworth/bootstrap-wysihtml5/issues/183
"stylesheets": [] //CSS stylesheets to load

Best regards!

**Comment by farabf33** [comment]
open bootstrap-wysihtml5.js, find `stylesheets: [` and edit the URL of `wysiwyg-color.css`.
