### ISSUE TITLE
PHP Notice:  Constant LARAVEL_START already defined in /opt/bitnami/frameworks/laravel/bootstrap/autoload.php on line 3

### ISSUE THREAD

**Issue by leeeunlim** [andrewelkins/Laravel-4-Bootstrap-Starter-Site#416]
Where is already defined constant LARAVEL_START?

**Comment by veb** [comment]
Probably here? https://github.com/andrewelkins/Laravel-4-Bootstrap/blob/master/public/index.php

**Comment by veb** [comment]
Probably here? https://github.com/andrewelkins/Laravel-4-Bootstrap-Starter-Site/blob/master/public/index.php

**Comment by veb** [comment]
[public/index.php](https://github.com/andrewelkins/Laravel-4-Bootstrap-Starter-Site/blob/5581a48a21bcc40356aa97b06dce7a95f1c262c4/public/index.php) 

``line 21`` loads the autoloader for bootstrap.

[bootstrap/autoload.php](https://github.com/andrewelkins/Laravel-4-Bootstrap-Starter-Site/blob/5581a48a21bcc40356aa97b06dce7a95f1c262c4/bootstrap/autoload.php)

line 3 on ```bootstrap/āutoload.php``` has ```define('LARAVEL_START', microtime(true));```

Hope that helps.

**Comment by leeeunlim** [comment]
Thanks a lot :) but...i knew that...
I want to know another constant LARAVEL_START defined..
and If i find that, should i comment that ???

**Comment by veb** [comment]
You could do something like this:

```
<?php
/* Note the use of quotes, this is important.  This example is checking
 * if the string 'TEST' is the name of a constant named TEST */
if (defined('TEST')) {
    echo TEST;
}
?>
```
[taken from PHP documentation](http://php.net/manual/en/function.defined.php)

**Comment by leeeunlim** [comment]
Thanks Thanks Thanks!!!......but sorry  i can't use that method....
because i cant see nothing in my server ip...
if i write that method...i can't see in my server.......

**Comment by leeeunlim** [comment]
I'm sorry...this is not a main problem....All of this is worked.....
i'm stupid. ..............Thanks !!!
