### ISSUE TITLE
composer install no work on windows

### ISSUE THREAD

**Issue by orijmm** [andrewelkins/Laravel-4-Bootstrap-Starter-Site#426]
When i run composer install in Step 2:

C:\xampp\htdocs\gestionop2>composer install
> php artisan clear-compiled

Warning: require(C:\xampp\htdocs\gestionop2\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\gestionop2\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\gestionop2\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\gestionop2\bootstrap\autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

**Comment by manoj10029** [comment]
Use composer.exe file for window installation and set php path in xampp dir

**Comment by orijmm** [comment]
thanks it work!
